version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "9090:8080" # Bahar 9090, Andar 8080 (Conflict se bachne ke liye)
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home # Data save karne ke liye
      - /var/run/docker.sock:/var/run/docker.sock # ⚠️ IMPORTANT: Taaki Jenkins Docker use kar sake
